# Docker file to compile PostgreSQL Japanese document

FROM ubuntu:trusty

MAINTAINER Tatsuo Ishii <ishii@sraoss.co.jp>

RUN cat /etc/os-release 
RUN apt-get update

RUN apt-get -y install git
RUN apt-get -y install build-essential libtool
RUN apt-get -y install docbook-dsssl openjade
ENV DOCDIR /jpug-doc
RUN git clone https://github.com/pgsql-jp/jpug-doc.git
ADD build.sh /tmp/
CMD /tmp/build.sh
